# Generated by Django 4.2.8 on 2023-12-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.TextField(null=True),
        ),
    ]
