# Generated by Django 4.2.8 on 2023-12-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=False),
        ),
    ]
