# Generated by Django 4.2.8 on 2023-12-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_friend_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='conversation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.messages'),
        ),
        migrations.AddField(
            model_name='messages',
            name='participants',
            field=models.ManyToManyField(related_name='conversation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
