# Generated by Django 4.2.8 on 2023-12-21 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_remove_chat_is_read_remove_chat_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
