# Generated by Django 4.2.8 on 2023-12-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_alter_messages_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='participants',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
